name: APK CD

on:
  push:
    tags:
      - 'v*'
      - 'v*.*'
  pull_request:
    tags:
      - 'v*'
      - 'v*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
            name: watertime
            path: app/build/outputs/apk/debug/app-debug.apk

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/debug/app-debug.apk
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false